# name: CI and Deploy to Server

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '20.10.0'

#     - name: Install dependencies
#       run: npm install

#     - name: Build project
#       run: npm run build

#     - name: Execute remote commands via SSH
#       uses: appleboy/ssh-action@v1.0.3
#       with:
#         host: ${{ secrets.SERVER_IP }}
#         username: root
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           # git config --global --add safe.directory /root/projects/favs_dev
#           mkdir -p /root/projects/favs_dev
#           cd /root/projects/favs_dev
#           if [ -d ".git" ]; then
#             git pull
#           else
#             git clone https://github.com/farzot/Favs.git .
#           fi
#           echo "${{ secrets.ENV_FILE_DEV }}" > /root/projects/favs_dev/.env
#           npm i
#           npm run build
#           pm2 reload favs_dev || pm2 start dist/main.js --name "favs_dev"
#           pm2 save

name: CI and Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Execute remote commands via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p /root/projects/favs_dev/
          cd /root/projects/favs_dev/
          if [ -d ".git" ]; then
            git pull https://github.com/farzot/Favs.git
          else
            git clone https://github.com/farzot/Favs.git .
          fi
          echo "${{ secrets.ENV_FILE_DEV }}" > /root/projects/favs_dev/.env
          npm i
          npm run build
          pm2 restart favs_dev || pm2 start npm —name="favs_dev" — run start
          pm2 save
